import {getSession} from "./_lib/auth.js";
export async function onRequestGet({request,env}){
 const s=await getSession(request,env);if(s?.role!=="admin")return new Response("Accès administrateur requis.",{status:403});
 return new Response(`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Utilisateurs</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f6f8;font-family:Arial,sans-serif;color:#17212b}.wrap{max-width:760px;margin:40px auto;padding:20px}.top{display:flex;justify-content:space-between;align-items:center}.card{background:#fff;border:1px solid #dbe2e8;border-top:5px solid #f4c400;border-radius:18px;padding:22px;margin-top:18px;box-shadow:0 12px 30px #26374612}h1{margin:0;font-size:24px}input,select{width:100%;height:44px;border:1px solid #ccd6de;border-radius:10px;padding:0 12px;margin-top:8px;font-size:15px}button,a.btn{border:0;border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer;text-decoration:none}.primary{background:#005a9c;color:#fff}.light{background:#eaf0f4;color:#334155}.danger{background:#fff0f0;color:#b42318}.grid{display:grid;grid-template-columns:1.4fr .8fr .8fr 1.2fr auto;gap:10px;align-items:end}.user{display:flex;justify-content:space-between;align-items:center;padding:13px 0;border-bottom:1px solid #edf1f4}.user:last-child{border:0}.actions{display:flex;gap:7px}.muted{color:#687785;font-size:13px}.err{color:#b42318;font-size:13px;margin-top:10px}@media(max-width:620px){.grid{grid-template-columns:1fr}.user{align-items:flex-start;gap:12px;flex-direction:column}}</style></head><body><div class="wrap"><div class="top"><h1>Gestion des utilisateurs</h1><a class="btn light" href="/">Retour</a></div><div class="card"><b>Créer un utilisateur</b><div class="grid"><div><div class="muted">E-mail</div><input id="u" type="email" autocomplete="off" placeholder="prenom.nom@entreprise.fr"></div><div><div class="muted">Profil</div><select id="role"><option value="PSSR">PSSR</option><option value="COMMERCIAL">COMMERCIAL</option></select></div><div><div class="muted">PIN</div><input id="p" inputmode="numeric" type="password" maxlength="12" placeholder="6 à 12 chiffres"></div><div><div class="muted" id="scope-label">Départements attribués</div><input id="scope" autocomplete="off" placeholder="Ex. 27, 76, 78"></div><button id="add" class="primary">Créer</button></div><div id="err" class="err"></div></div><div class="card"><b>Utilisateurs</b><div id="list"></div></div></div><script>
const err=document.getElementById("err");async function req(method,body){const r=await fetch("/api/admin/users",{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||"Erreur");return j}
async function load(){const j=await req("GET");const l=document.getElementById("list");l.textContent="";if(!j.users.length){l.innerHTML='<p class="muted">Aucun utilisateur créé.</p>';return}j.users.forEach(x=>{const d=document.createElement("div");d.className="user";const info=document.createElement("div");const b=document.createElement("b");b.textContent=x.username;info.append(b);const m=document.createElement("div");m.className="muted";m.textContent=x.role+(x.scope?.departments?.length?" · Départements : "+x.scope.departments.join(", "):"");info.append(m);const a=document.createElement("div");a.className="actions";const reset=document.createElement("button");reset.className="light";reset.textContent="Changer PIN";reset.onclick=async()=>{const pin=prompt("Nouveau PIN (6 à 12 chiffres)");if(pin===null)return;try{await req("PATCH",{username:x.username,pin});alert("PIN modifié.")}catch(e){alert(e.message)}};const del=document.createElement("button");del.className="danger";del.textContent="Supprimer";del.onclick=async()=>{if(!confirm("Supprimer "+x.username+" ?"))return;try{await req("DELETE",{username:x.username});load()}catch(e){alert(e.message)}};a.append(reset,del);d.append(info,a);l.append(d)})}
const role=document.getElementById("role"),scope=document.getElementById("scope"),scopeLabel=document.getElementById("scope-label");function roleUI(){scopeLabel.textContent="Départements attribués";scope.placeholder="Ex. 27, 76, 78"}role.onchange=roleUI;roleUI();
document.getElementById("add").onclick=async()=>{err.textContent="";try{const r=role.value;const raw=scope.value.trim();await req("POST",{username:document.getElementById("u").value,pin:document.getElementById("p").value,role:r,scope:{departments:raw.split(",").map(x=>x.trim()).filter(Boolean)}});document.getElementById("u").value="";document.getElementById("p").value="";scope.value="";await load()}catch(e){err.textContent=e.message}};load().catch(e=>err.textContent=e.message);
</script></body></html>`,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}});
}