import { h } from '../lib/react.js';
import { formatCurrency } from '../utils/format.js';
import { Icon } from './Icons.js';

export function CrmDrawer({ row, onClose }) {
    const isOpen = Boolean(row);
    const isClient = row?.typeCompte === 'CL';

    return h('div', null,
        h('div', { className: `fixed inset-y-0 right-0 z-[9999] flex w-full max-w-md transform flex-col border-l border-gray-200 bg-white shadow-[0_0_40px_rgba(0,0,0,0.1)] transition-transform duration-300 ease-in-out dark:border-slate-800 dark:bg-slate-900 ${isOpen ? 'translate-x-0' : 'translate-x-full'}` },
            row && [
                h('div', { key: 'head', className: 'flex shrink-0 items-start justify-between border-b border-gray-200 bg-gray-50 px-6 py-5 dark:border-slate-800 dark:bg-slate-950' },
                    h('div', null,
                        h('div', { className: 'mb-1 flex items-center gap-2' },
                            h('span', { className: `rounded border px-2 py-0.5 text-[10px] font-bold uppercase ${isClient ? 'border-emerald-200 bg-emerald-100 text-emerald-800' : 'border-amber-200 bg-amber-100 text-amber-800'}` }, isClient ? 'Client' : 'Prospect'),
                            row.isTop200 && h('span', { className: 'rounded border border-amber-200 bg-amber-100 px-2 py-0.5 text-[10px] font-bold text-amber-700' }, 'TOP 200'),
                        ),
                        h('h2', { className: 'font-display text-xl font-black text-gray-900 dark:text-white' }, row.name),
                        h('p', { className: 'font-mono text-xs font-medium text-gray-500' }, `SIRET: ${row.siret}`),
                    ),
                    h('button', { type: 'button', onClick: onClose, className: 'rounded-full border border-gray-200 bg-white p-2 text-gray-500 shadow-sm transition hover:text-gray-800 dark:border-slate-700 dark:bg-slate-800 dark:hover:text-white' },
                        h(Icon, { name: 'close', className: 'h-5 w-5' }),
                    ),
                ),
                h('div', { key: 'body', className: 'flex-1 space-y-6 overflow-y-auto p-6' },
                    h('section', null,
                        h('h3', { className: 'mb-3 text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-slate-500' }, 'Informations de Contact'),
                        h('div', { className: 'space-y-3 rounded-xl border border-gray-100 bg-gray-50 p-4 dark:border-slate-700/50 dark:bg-slate-800/50' },
                            h('div', { className: 'flex items-start gap-3' },
                                h(Icon, { name: 'mapPin', className: 'mt-0.5 h-4 w-4 shrink-0 text-komatsu-500' }),
                                h('span', { className: 'text-sm text-gray-700 dark:text-slate-300' }, row.address),
                            ),
                            h('div', { className: 'flex items-center gap-3' },
                                h(Icon, { name: 'phone', className: 'h-4 w-4 shrink-0 text-gray-400' }),
                                h('span', { className: 'text-sm font-medium text-gray-700 dark:text-slate-300' }, row.phone),
                            ),
                            h('div', { className: 'flex items-center gap-3' },
                                h(Icon, { name: 'user', className: 'h-4 w-4 shrink-0 text-gray-400' }),
                                h('span', { className: 'text-sm text-gray-700 dark:text-slate-300' }, 'Vendeur: ', h('strong', { className: 'text-gray-900 dark:text-white' }, row.vendeur)),
                            ),
                        ),
                    ),
                    h('section', null,
                        h('h3', { className: 'mb-3 text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-slate-500' }, 'Données Financières'),
                        h('div', { className: 'grid grid-cols-2 gap-3' },
                            h('div', { className: 'rounded-xl border border-gray-100 bg-gray-50 p-3 dark:border-slate-700/50 dark:bg-slate-800/50' },
                                h('div', { className: 'mb-1 text-[10px] font-semibold uppercase text-gray-500' }, 'CA Global'),
                                h('div', { className: 'font-display text-lg font-bold text-gray-900 dark:text-white' }, formatCurrency(row.caGlobal)),
                            ),
                            h('div', { className: 'rounded-xl border border-komatsu-200 bg-komatsu-50 p-3 dark:border-komatsu-500/20 dark:bg-komatsu-500/10' },
                                h('div', { className: 'mb-1 text-[10px] font-semibold uppercase text-komatsu-700 dark:text-komatsu-400' }, 'CA PCS'),
                                h('div', { className: 'font-display text-lg font-bold text-komatsu-700 dark:text-komatsu-400' }, formatCurrency(row.caPCS)),
                            ),
                        ),
                    ),
                    h('section', null,
                        h('h3', { className: 'mb-3 text-xs font-bold uppercase tracking-wider text-gray-400 dark:text-slate-500' }, 'Parc Machine Connu'),
                        h('div', { className: 'rounded-xl border border-gray-100 bg-gray-50 p-4 dark:border-slate-700/50 dark:bg-slate-800/50' },
                            h('div', { className: 'mb-2 text-sm font-semibold text-gray-800 dark:text-slate-200' }, row.machines || 'Aucune machine'),
                            h('div', { className: 'text-xs text-gray-500 dark:text-slate-400' }, 'N/S : ', h('span', { className: 'font-mono' }, row.serials || 'N/A')),
                        ),
                    ),
                    h('div', { className: 'flex gap-3 pt-4' },
                        h('button', { type: 'button', className: 'flex-1 rounded-xl bg-komatsu-500 py-2.5 font-bold text-slate-900 shadow-md transition hover:bg-komatsu-400' }, 'Créer Opportunité'),
                        h('button', { type: 'button', className: 'flex-1 rounded-xl border border-gray-200 bg-white py-2.5 font-bold text-gray-700 shadow-sm transition hover:border-gray-300 dark:border-slate-700 dark:bg-slate-800 dark:text-white dark:hover:border-slate-600' }, 'Saisir CR Visite'),
                    ),
                ),
            ],
        ),
        h('button', {
            type: 'button',
            onClick: onClose,
            className: `fixed inset-0 z-[9998] bg-slate-900/40 backdrop-blur-sm transition-opacity duration-300 ${isOpen ? 'opacity-100' : 'pointer-events-none opacity-0'}`,
            'aria-label': 'Fermer la fiche CRM',
        }),
    );
}
