import { h } from '../lib/react.js';
import { Accordion } from './Accordion.js';
import { Icon } from './Icons.js';

export function FiltersSidebar({ filters, onFilterChange, onReset, activePssr, onOpenPssrSelector }) {
    const update = (key, value) => onFilterChange({ ...filters, [key]: value });

    return h('aside', { className: 'z-10 flex w-[360px] shrink-0 flex-col overflow-y-auto border-r border-gray-200 bg-white shadow-[4px_0_24px_rgba(0,0,0,0.02)] dark:border-slate-800 dark:bg-slate-900' },
        h('div', { className: 'sticky top-0 z-20 flex items-center justify-between border-b border-gray-100 bg-white/80 p-5 backdrop-blur-md dark:border-slate-800 dark:bg-slate-900/80' },
            h('h2', { className: 'flex items-center gap-2 font-display text-sm font-bold text-gray-800 dark:text-slate-100' },
                h(Icon, { name: 'sliders', className: 'h-4 w-4 text-komatsu-500' }),
                'Filtres de recherche',
            ),
            h('button', { type: 'button', onClick: onReset, className: 'rounded-md bg-gray-100 px-2 py-1 text-[11px] font-semibold text-gray-500 transition hover:text-komatsu-600 dark:bg-slate-800 dark:text-slate-400 dark:hover:text-white' }, 'Réinitialiser'),
        ),
        h('div', { className: 'space-y-4 p-4' },
            h('div', { className: 'rounded-xl border border-komatsu-200 bg-komatsu-50 p-4 shadow-sm dark:border-komatsu-500/20 dark:bg-komatsu-500/10' },
                h('div', { className: 'flex items-start justify-between gap-3' },
                    h('div', null,
                        h('div', { className: 'text-[10px] font-bold uppercase tracking-widest text-komatsu-700 dark:text-komatsu-400' }, 'Secteur actif'),
                        h('div', { className: 'mt-1 font-display text-sm font-black text-gray-950 dark:text-white' }, activePssr ? activePssr.name : 'Tous les PSSR'),
                        h('div', { className: 'mt-1 text-[11px] font-medium text-gray-500 dark:text-slate-400' }, activePssr ? `Départements : ${activePssr.departments.join(', ')}` : 'Aucun filtrage département'),
                    ),
                    h('button', { type: 'button', onClick: onOpenPssrSelector, className: 'shrink-0 rounded-lg bg-white px-3 py-1.5 text-[11px] font-bold text-gray-700 shadow-sm ring-1 ring-gray-200 transition hover:text-komatsu-700 dark:bg-slate-900 dark:text-slate-200 dark:ring-slate-700' }, 'Changer'),
                ),
            ),
            h(Accordion, { title: '1. Client / Prospect', defaultOpen: true },
                h('div', { className: 'mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 dark:border-amber-500/20 dark:bg-amber-500/10' },
                    h('label', { className: 'flex cursor-pointer items-center space-x-3' },
                        h('input', { type: 'checkbox', checked: filters.top200, onChange: (event) => update('top200', event.target.checked), className: 'modern-checkbox' }),
                        h('span', { className: 'text-[12px] font-bold text-amber-700 dark:text-amber-500' }, 'Afficher uniquement le TOP 200'),
                    ),
                ),
                h('div', null,
                    h('label', { className: 'modern-label' }, 'Statut du compte'),
                    h('select', { value: filters.typeCompte, onChange: (event) => update('typeCompte', event.target.value), className: 'modern-input' },
                        h('option', { value: '' }, 'Tous les statuts'),
                        h('option', { value: 'CL' }, 'Client (CL)'),
                        h('option', { value: 'PR' }, 'Prospect (PR)'),
                    ),
                ),
                h('div', null,
                    h('label', { className: 'modern-label' }, 'Dénomination (Nom)'),
                    h('input', { type: 'text', value: filters.nom, onChange: (event) => update('nom', event.target.value), placeholder: 'Ex: COLAS, WATELET...', className: 'modern-input' }),
                ),
                h('div', null,
                    h('label', { className: 'modern-label' }, 'Ville'),
                    h('input', { type: 'text', value: filters.ville, onChange: (event) => update('ville', event.target.value), placeholder: 'Ex: POISSY, BUC...', className: 'modern-input' }),
                ),
            ),
            h(Accordion, { title: '2. Parc & Flotte Machines' },
                h('div', { className: 'mb-4 rounded-lg border border-purple-200 bg-purple-50 p-3 dark:border-purple-500/20 dark:bg-purple-500/10' },
                    h('label', { className: 'flex cursor-pointer items-center space-x-3' },
                        h('input', { type: 'checkbox', checked: filters.newMachine, onChange: (event) => update('newMachine', event.target.checked), className: 'modern-checkbox' }),
                        h('span', { className: 'text-[12px] font-bold text-purple-700 dark:text-purple-400' }, 'Machines récentes (< 1 an)'),
                    ),
                ),
                h('div', null,
                    h('label', { className: 'modern-label' }, 'Recherche par N° de Série'),
                    h('input', { type: 'text', value: filters.serial, onChange: (event) => update('serial', event.target.value), placeholder: 'Ex: H80528...', className: 'modern-input mb-3' }),
                ),
                h('div', null,
                    h('label', { className: 'modern-label' }, 'Modèle de Machine'),
                    h('select', { value: filters.modele, onChange: (event) => update('modele', event.target.value), className: 'modern-input' },
                        h('option', { value: '' }, 'Tous les modèles'),
                        h('option', { value: 'PC20E-6' }, 'PC20E-6 (Électrique)'),
                        h('option', { value: 'PC88MR-11' }, 'PC88MR-11'),
                        h('option', { value: 'WA320-8' }, 'WA320-8'),
                        h('option', { value: 'PW148-11' }, 'PW148-11'),
                    ),
                ),
            ),
            h(Accordion, { title: '3. Potentiel Financier' },
                h('div', { className: 'rounded-lg border border-gray-100 bg-gray-50 p-3 dark:border-slate-800 dark:bg-slate-950' },
                    h('div', { className: 'mb-2 flex justify-between text-[10px] text-gray-500 dark:text-slate-400' },
                        h('span', { className: 'font-bold uppercase' }, 'CA PCS Minimum (€)'),
                        h('span', { className: 'text-xs font-bold text-komatsu-600 dark:text-komatsu-400' }, `${filters.caMin} €`),
                    ),
                    h('input', { type: 'range', min: '0', max: '25000', step: '500', value: filters.caMin, onChange: (event) => update('caMin', Number(event.target.value)), className: 'h-1.5 w-full cursor-pointer appearance-none rounded-lg bg-gray-300 dark:bg-slate-700' }),
                ),
            ),
        ),
    );
}
