import { h, useEffect, useRef, useState } from '../lib/react.js';
import { formatCurrency } from '../utils/format.js';
import { Icon } from './Icons.js';
export function MapView({data,darkMode,routeActive,prospectFocus,onToggleRoute,onOpenCrm}){
 const mapNodeRef=useRef(null),mapRef=useRef(null),markersRef=useRef(null),tileLayerRef=useRef(null),routeRef=useRef(null),prospectMarkerRef=useRef(null);const [routeTime,setRouteTime]=useState('Calcul...'),[routeItems,setRouteItems]=useState([]);
 useEffect(()=>{if(!mapNodeRef.current||mapRef.current||!window.L)return;mapRef.current=window.L.map(mapNodeRef.current).setView([48.866667,2.033333],10);markersRef.current=window.L.layerGroup().addTo(mapRef.current)},[]);
 useEffect(()=>{if(!mapRef.current||!window.L)return;if(tileLayerRef.current)mapRef.current.removeLayer(tileLayerRef.current);tileLayerRef.current=window.L.tileLayer(darkMode?'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png':'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(mapRef.current)},[darkMode]);
 useEffect(()=>{if(!mapRef.current||!markersRef.current||!window.L)return;markersRef.current.clearLayers();const bounds=[];data.forEach(item=>{if(!item.lat||!item.lng)return;const icon=window.L.divIcon({className:'custom-div-icon',html:`<div style="background:${item.typeCompte==='CL'?'#10b981':'#f59e0b'};width:24px;height:24px;border-radius:50%;border:2px solid white;color:white;text-align:center;line-height:20px;font-weight:700">${item.typeCompte}</div>`,iconSize:[24,24],iconAnchor:[12,12]});const marker=window.L.marker([item.lat,item.lng],{icon}).addTo(markersRef.current);marker.bindPopup(`<b>${item.name}</b><br>${item.typeCompte==='CL'?'Client':'Prospect'} - Dept ${item.dept}<br>CA PCS: ${formatCurrency(item.caPCS)}`);marker.on('click',()=>onOpenCrm(item.id));bounds.push([item.lat,item.lng])});if(bounds.length)mapRef.current.fitBounds(bounds,{padding:[35,35],maxZoom:11})},[data,onOpenCrm]);
 useEffect(()=>{if(!prospectFocus||!mapRef.current||!window.L)return;let cancelled=false;(async()=>{let lat=Number(prospectFocus.lat),lng=Number(prospectFocus.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)){const q=[prospectFocus.address,prospectFocus.postalCode,prospectFocus.city,'France'].filter(Boolean).join(' ');if(!q)return;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=fr&q=${encodeURIComponent(q)}`);const j=await r.json();if(!j?.length||cancelled)return;lat=Number(j[0].lat);lng=Number(j[0].lon)}catch{return}}if(cancelled)return;if(prospectMarkerRef.current)prospectMarkerRef.current.remove();const icon=window.L.divIcon({className:'commercial-prospect-pin',html:'<div style="background:#f59e0b;border:3px solid white;border-radius:50%;width:34px;height:34px;box-shadow:0 3px 10px #0006;color:white;font-weight:900;text-align:center;line-height:28px">P</div>',iconSize:[34,34],iconAnchor:[17,17]});prospectMarkerRef.current=window.L.marker([lat,lng],{icon,zIndexOffset:2000}).addTo(mapRef.current).bindPopup(`<b>${prospectFocus.name||'Prospect'}</b><br>${[prospectFocus.address,prospectFocus.postalCode,prospectFocus.city].filter(Boolean).join(' ')}<br><small>SIREN ${prospectFocus.siren||''} · SIRET ${prospectFocus.siret||''}</small>`).openPopup();mapRef.current.setView([lat,lng],16,{animate:true});setTimeout(()=>mapRef.current?.invalidateSize(),50)})();return()=>{cancelled=true}},[prospectFocus]);
 useEffect(()=>{if(!mapRef.current||!window.L)return;if(routeRef.current){mapRef.current.removeControl(routeRef.current);routeRef.current=null}if(!routeActive){setRouteItems([]);setRouteTime('Calcul...');return}const items=data.filter(x=>x.lat&&x.lng).slice(0,8);setRouteItems(items);if(!items.length||!window.L.Routing){setRouteTime(items.length?'Indisponible':'Aucune étape');return}routeRef.current=window.L.Routing.control({waypoints:items.map(x=>window.L.latLng(x.lat,x.lng)),routeWhileDragging:false,addWaypoints:false,lineOptions:{styles:[{color:darkMode?'#facc15':'#0f172a',weight:5,opacity:.9}]},createMarker:()=>null}).addTo(mapRef.current);routeRef.current.on('routesfound',e=>{const mins=Math.round(e.routes[0].summary.totalTime/60);setRouteTime(`${Math.floor(mins/60)}h ${mins%60}min`)})},[data,darkMode,routeActive]);
 return h('div',{className:'absolute inset-0'},h('div',{id:'map',ref:mapNodeRef,className:'z-0'}),routeActive&&h('div',{className:'absolute right-4 top-4 z-[1000] w-[340px] rounded-2xl border bg-white/95 p-4 shadow-2xl dark:bg-slate-950/95'},h('div',{className:'flex justify-between font-bold'},h('span',null,'Itinéraire Routier'),h('button',{type:'button',onClick:onToggleRoute},h(Icon,{name:'close',className:'h-4 w-4'}))),h('div',{className:'mt-2 text-xs'},`Durée estimée : ${routeTime}`),h('div',{className:'mt-3 text-xs'},routeItems.map((x,i)=>h('div',{key:x.id,className:'py-1'},`${i+1}. ${x.name} — ${x.ville}`)))));
}
